#! /bin/bash
if [[ -d /proc/acpi/battery ]] ; then
    max=$(
        grep -h 'last full capacity' /proc/acpi/battery/BAT*/info |
            cut -f2 -d: | tr -d '\n' | sed 's/m[AW]h/+/g'
    )
    current=$(
        grep -h 'remaining capacity' /proc/acpi/battery/BAT*/state |
            cut -f2 -d: | tr -d '\n' | sed 's/m[AW]h/+/g'
    )
else
    max=$(cat /sys/class/power_supply/BAT*/charge_full | tr '\n' +)
    current=$(cat /sys/class/power_supply/BAT*/charge_now | tr '\n' +)
fi

percent=$( bc -l <<< "100 * ($current 0) / ($max 0)" )

if [[ $1 ]] ; then
    cols=$(stty --all | grep -o 'columns [0-9]*')
    cols=${cols#* }
    rmax=cols
    rperc=$(( ${percent%.*} * cols / 100 ))
    for (( i=1; i<rmax; i++ )) ; do
        printf -
    done
    echo
    for (( i=1; i<rmax; i++ )) ; do
        if ((i<rperc)) ; then
            printf $'\e[0;32mX'
        else
            printf $'\e[1;31m|'
        fi
    done
    echo $'\e[0m'
    for (( i=1; i<rmax; i++ )) ; do
        printf -
    done
    echo
else
    echo $percent
fi
