#!/bin/bash
# Run blead perl instead of the system one. Just prefix your command
# with "blead": handles "blead cpan", "blead perldoc open" or "blead
# script.pl".

unset PERL5LIB PERL_MM_OPT PERL_MB_OPT PERL_LOCAL_LIB_ROOT
cmd=$1

shopt -s nullglob
exec=("$HOME"/localperl/bin/"$cmd"*)
if [[ ${exec[0]} ]] ; then
    shift
    "${exec[0]}" "$@"
else
    perl=("$HOME"/localperl/bin/perl*)
    "${perl[0]}" "$@"
fi
