#!/bin/bash
# Run blead perl instead of the system one. Just prefix your command
# with "blead": handles "blead cpan", "blead perldoc open" or "blead
# script.pl".

bleadpath="$HOME"/blead/bin

unset PERL5LIB PERL_MM_OPT PERL_MB_OPT PERL_LOCAL_LIB_ROOT
cmd=${1-perl}

shopt -s nullglob
shopt -s extglob
lc=$(locale)
LC_ALL=C
exec=("$bleadpath/$cmd"*)
eval $lc
if [[ ${exec[0]} ]] ; then
    shift
    "${exec[0]}" "$@"
else
    lc=$(locale)
    LC_ALL=C
    perl=("$bleadpath/perl"*)
    eval $lc
    "${perl[0]}" "$@"
fi
