#!/bin/bash
state=$(bluetoothctl show)
if (( $? )) ; then
    state=blocked
fi

if [[ $state = blocked ]] ; then
    /usr/sbin/rfkill unblock bluetooth
fi
if [[ $state = *Powered:' 'yes* ]] ; then
    bluetoothctl power off
else
    bluetoothctl power on
fi
